name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'README.md'
      - '.idea/**'
      - 'images/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Restore gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.npm
          key: ${{ runner.os }}-gradle-npm-${{ hashFiles('**/build.gradle.kts') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-gradle-npm
      - name: Build plugin
        run: echo ::set-env name=PLUGIN_VERSION::$(./gradlew properties -q | grep "version:" | awk '{print $2}') && ./gradlew buildPlugin
      - name: Run Intellij Plugin Verifier
        uses: thepieterdc/intellij-plugin-verifier-action@v1.1.2
        with:
          plugin: "build/distributions/intellij-pdf-viewer-${{ env.PLUGIN_VERSION }}.zip"
          versions: |
            202.4357.23-EAP-SNAPSHOT
            LATEST-EAP-SNAPSHOT
      - name: Upload plugin
        uses: actions/upload-artifact@v1
        with:
          name: "intellij-pdf-viewer-${{ env.PLUGIN_VERSION }}-${{ github.sha }}.zip"
          path: "build/distributions/intellij-pdf-viewer-${{ env.PLUGIN_VERSION }}.zip"
