name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build plugin
        run: echo ::set-env name=PLUGIN_VERSION::$(./gradlew properties -q | grep "version:" | awk '{print $2}') && ./gradlew buildPlugin
      - name: Run Intellij Plugin Verifier
        uses: thepieterdc/intellij-plugin-verifier-action@v1.1.2
        with:
          plugin: "build/distributions/intellij-pdf-viewer-${{ env.PLUGIN_VERSION }}.zip"
          versions: |
            202.4357.23-EAP-SNAPSHOT
            LATEST-EAP-SNAPSHOT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "build/distributions/intellij-pdf-viewer-${{ env.PLUGIN_VERSION }}.zip"
          asset_name: "intellij-pdf-viewer-${{ env.PLUGIN_VERSION }}.zip"
          asset_content_type: application/zip
